- hosts: kafkamanager
  sudo: True
  gather_facts: yes
  remote_user: "{{ansible_ssh_user}}"

  tasks:
    - name: "Stop kafka manager container"
      shell: "sudo docker stop {{kafka_mgr_container}}"
      ignore_errors: yes
