- hosts: zk
  sudo: True
  gather_facts: yes
  remote_user: "{{ansible_ssh_user}}"

  tasks:
    - name: Stop zookeeper docker container
      shell: "sudo docker stop {{zookeeper_container_name}}"
      ignore_errors: yes
