- hosts: kafka
  sudo: True
  gather_facts: yes
  remote_user: "{{ansible_ssh_user}}"

  tasks:
   - name: Stop kafka docker container
     shell: "sudo docker stop {{kafka_container_name}}"
     ignore_errors: yes
